version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ichack-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9ga981wfnewx"
s3_prefix = "ichack-stack"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
